module.exports = {
  // 'no-restricted-syntax': 0,
  // 'max-len': 0,
  // 'no-alert': 0,
  // 'no-labels': 0,
  // 'no-void': 0,
  // 'no-eq-null': 0,
  // 'no-return-assign': 0,
  // 'radix': 0,
  'no-unused-expressions': 0,
  // 'no-await-in-loop': 0,
  // 'vue/return-in-computed-property': 0,
  // 'max-lines': 0,
  'max-lines-per-function': 0,
  // 'no-case-declarations': 0,
  // 'vue/valid-v-model': 0,
  // 'vue/no-use-v-if-with-v-for': 0,

  'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
  'no-undef': 0,
  'no-unused-vars': 0,
  camelcase: 0,
  'no-nested-ternary': 0,
  'no-underscore-dangle': 0,
  'no-plusplus': 0,
  'no-lonely-if': 0,
  'func-names': 0,
  'no-loop-func': 0,
  'vars-on-top': 0, // 加no-var
  'no-param-reassign': 0,
  'default-case': 0,
  'consistent-return': 0,
  complexity: 0, // complexity: ['warn', 10],
  'vue/no-unused-vars': 0,
  'vue/require-prop-type-constructor': 0
}
